[paths]
benchmarks_dir = "benchmarks" # QASM files of benchmarks used for experiments
results_dir = "results" # experiments results
benchmarks_stats = "benchmarks/stats.csv"

[paths.qiskit_outputs]
circuits = "circuits" # circuits that qiskit transpiler produces
stats = "stats.csv" # time taken by the transpiler